export { AlertDialogAction as Action } from './alert-dialog-action';
export { AlertDialogCancel as Cancel } from './alert-dialog-cancel';
export { AlertDialogContent as Content } from './alert-dialog-content';
export { AlertDialogDescription as Description } from './alert-dialog-description';
export { AlertDialogFooter as Footer } from './alert-dialog-footer';
export { AlertDialogHeader as Header } from './alert-dialog-header';
export { AlertDialogRoot as Root } from './alert-dialog-root';
export { AlertDialogTitle as Title } from './alert-dialog-title';
export { AlertDialogTrigger as Trigger } from './alert-dialog-trigger';